- name: Install general productivity packages
  become: true
  apt:
    name: ['flameshot', 'copyq', 'qbittorrent', 'ripgrep', 'fzf', 'tmux', 'resolvconf', 'wireguard', 'pass']
  tags:
    - productivity
    - core
